name: tinkoff_acquiring_flutter
description: Flutter Tinkoff Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 3.0.11
repository: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tinkoff_acquiring: ^3.0.11
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: